videos:
  - id: BV1at4y1h7X4
    source: bilibili
    url: https://www.bilibili.com/video/BV1at4y1h7X4/
  - id: CZdDu01dGeM
    source: youtube
    url: https://www.youtube.com/watch?v=CZdDu01dGeM
  - id: BV1zN4y1H7d7
    source: bilibili
    url: https://www.bilibili.com/video/BV1zN4y1H7d7/
  - id: V6K4o0Ns9eQ
    source: youtube
    url: https://www.youtube.com/watch?v=V6K4o0Ns9eQ
  - id: YpSk_c0j3VY
    source: youtube
    url: https://www.youtube.com/watch?v=YpSk_c0j3VY
  - id: 4GQe9btEkqg
    source: youtube
    url: https://www.youtube.com/watch?v=4GQe9btEkqg
