videos:
  - id: BV1f64y1V7f2
    source: bilibili
    url: https://www.bilibili.com/video/BV1f64y1V7f2/
  - id: IAUFWQPTmAA
    source: youtube
    url: https://www.youtube.com/watch?v=IAUFWQPTmAA
  - id: wrHVgPEdN5g
    source: youtube
    url: https://www.youtube.com/watch?v=wrHVgPEdN5g
  - id: SSUKY6MwyN8
    source: youtube
    url: https://www.youtube.com/watch?v=SSUKY6MwyN8
  - id: sy45qnchmEg
    source: youtube
    url: https://www.youtube.com/watch?v=sy45qnchmEg
  - id: 6OwSbNsUop4
    source: youtube
    url: https://www.youtube.com/watch?v=6OwSbNsUop4
