videos:
  - id: 0y3O90vyKNo
    source: youtube
    url: https://www.youtube.com/watch?v=0y3O90vyKNo
  - id: sy45qnchmEg
    source: youtube
    url: https://www.youtube.com/watch?v=sy45qnchmEg
  - id: wrHVgPEdN5g
    source: youtube
    url: https://www.youtube.com/watch?v=wrHVgPEdN5g
  - id: IAUFWQPTmAA
    source: youtube
    url: https://www.youtube.com/watch?v=IAUFWQPTmAA
  - id: CZdDu01dGeM
    source: youtube
    url: https://www.youtube.com/watch?v=CZdDu01dGeM
  - id: 6OwSbNsUop4
    source: youtube
    url: https://www.youtube.com/watch?v=6OwSbNsUop4
  - id: 4GQe9btEkqg
    source: youtube
    url: https://www.youtube.com/watch?v=4GQe9btEkqg
  - id: V6K4o0Ns9eQ
    source: youtube
    url: https://www.youtube.com/watch?v=V6K4o0Ns9eQ
  - id: YpSk_c0j3VY
    source: youtube
    url: https://www.youtube.com/watch?v=YpSk_c0j3VY
  - id: SSUKY6MwyN8
    source: youtube
    url: https://www.youtube.com/watch?v=SSUKY6MwyN8
  - id: BV1at4y1h7X4
    source: bilibili
    url: https://www.bilibili.com/video/BV1at4y1h7X4/
  - id: BV1zN4y1H7d7
    source: bilibili
    url: https://www.bilibili.com/video/BV1zN4y1H7d7/
  - id: BV1fN411G7HB
    source: bilibili
    url: https://www.bilibili.com/video/BV1fN411G7HB/
  - id: BV1f64y1V7f2
    source: bilibili
    url: https://www.bilibili.com/video/BV1f64y1V7f2/
